version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: poetry run gunicorn DjangoOnDocker.wsgi:application --bind 0.0.0.0:8000
    volumes:
#      - static_volume:/home/app/web/staticfiles
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB_PROD}

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "1337:80"

    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: